config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers:{ 
    registrations: 'users/registrations',
    sessions: 'users/sessions' 
  }
  
  root 'top#index'
  resources :toilet_places do
    resources :reviews, only: %i[new create edit update destroy]
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :toilet_place
  
  validates :content, presence: true
  
  scope :default_order, -> { order(id: :asc) }
end

app/models/toilet_place.rb
class ToiletPlace < ApplicationRecord
  belongs_to :user
  has_many :reviews, dependent: :destroy
  
  geocoded_by :address
  before_validation :geocode, if: :address_changed?
  
  validates :name, presence: true
  validates :address, presence: true
  validate :geolocation_present
  
  scope :default_order, -> { order(id: :asc) }

  private

  def geolocation_present
    if longitude.nil? || latitude.nil?
      errors.add(:base, "正しい住所または名称を入力してください")
    end
  end

  def self.ransackable_attributes(auth_object = nil)
    %w(name address)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :toilet_places
  has_many :reviews

  def self.ransackable_attributes(auth_object = nil)
    %w(name email)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[edit update destroy]
  
  def create
    @review = current_user.reviews.build(review_params)
    if @review.save
      redirect_to toilet_place_path(@review.toilet_place.id), notice: 'レビューを投稿しました'
    else
      redirect_to toilet_place_path(@review.toilet_place.id), alert: 'レビューを投稿に失敗しました。'
    end
  end
  
  def edit
  end
  
  def update
    if @review.update(review_params)
      redirect_to toilet_place_path(@review.toilet_place_id), notice: 'レビューを更新しました'
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    @review.destroy!
    redirect_to toilet_place_path(@review.toilet_place_id), notice: 'レビューを削除しました'
  end
  
  private
  
  def set_review
    @review = current_user.reviews.find(params[:id])
  end
  
  def review_params
    params.require(:review).permit(:content, :toilet_place_id)
  end
end

app/controllers/toilet_places_controller.rb
class ToiletPlacesController < ApplicationController
  before_action :set_toilet_place, only: %i[show edit update destroy]
  before_action :set_toilet_place_map, only: %i[index show create new edit search]

  def index
    @q = ToiletPlace.ransack(params[:q])
    @results = @q.result.default_order.page(params[:page]).per(8)
  end
  
  def show
    @review  = Review.new
    @reviews = @toilet_place.reviews.default_order
  end
  
  def new
    @toilet_place = ToiletPlace.new
  end
  
  def create
    @toilet_place = ToiletPlace.new(toilet_place_params)
    @toilet_place.user_id = current_user.id
    
    if @toilet_place.save
      redirect_to root_path, notice: 'トイレの場所を登録しました'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end
  
  def update
    if @toilet_place.update(toilet_place_params)
      redirect_to root_path, notice: 'トイレの場所を更新しました'
    else
      render :edit, status: :unprocessable_entity
    end
  end
  
  def destroy
    @toilet_place.destroy!
    redirect_to root_path, notice: 'トイレの場所を削除しました'
  end
  
  private

  def set_toilet_place
    @toilet_place = ToiletPlace.find(params[:id])
  end
  
  def toilet_place_params
    params.require(:toilet_place).permit(:name, :address, :longitude, :latitude)
  end

  def set_toilet_place_map
    @toilet_places = ToiletPlace.default_order.page(params[:page]).per(10)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @toilet_places = ToiletPlace.default_order
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  def new
    @toilet_places = ToiletPlace.default_order
    super
  end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    @toilet_places = ToiletPlace.default_order
    super
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/toilet_places_helper.rb
module ToiletPlacesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/layouts/_sidebar.html.erb
<div class="col-md-3 col-12 scrollable-sidebar">
  <%= render 'shared/title' %>
  <ul class="nav nav-tabs mt-3" id="myTabs">
    <li class="nav-item">
      <a class="nav-link active" id="tab1-tab" data-bs-toggle="tab" href="#tab1">経路案内</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" id="tab2-tab" data-bs-toggle="tab" href="#tab2">各リンク先</a>
    </li>
  </ul>
  
  <div class="tab-content mt-3 ms-2">
    <div class="tab-pane active" id="tab1">
      <div id="routeDetails" class='mb-2'></div>
    </div>
    <div class="tab-pane" id="tab2">
      <% if user_signed_in? %>
        <ul class='p-4 ms-4'>
          <li class='mb-3'><%= link_to 'トイレの場所登録', new_toilet_place_path%></li>
          <li class='mb-3'><%= link_to 'トイレの一覧画面', toilet_places_path%></li>
          <li class='mb-3'><%= link_to 'ログアウト', destroy_user_session_path, data: { turbo_method: :delete } %></li>
        </ul>
      <% else %>
        <ul class='p-4 ms-4'>
          <li class='mb-3'><%= link_to 'トイレの一覧画面', toilet_places_path%></li>
          <li class='mb-3'><%= link_to 'アカウント登録', new_user_registration_path%></li>
          <li class='mb-3'><%= link_to 'ログイン', new_user_session_path%></li>
        </ul>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToiletNavigator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%= favicon_link_tag('toilet_nav.ico') %>
  </head>

  <body>
    <%= render 'shared/flash' %>
    <%= yield %>
  </body>
</html>

app/views/reviews/edit.html.erb
<div class='w-50 mx-auto mt-3'>
  <%= simple_form_for @review, url: toilet_place_review_path(@review.toilet_place.id, @review) do |f|%>
    <%= f.input :content, input_html: { rows: 5 } %>
    <%= f.input :toilet_place_id, as: :hidden, input_html: { value: @review.toilet_place.id } %>
    <%= f.button :submit, class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div class="alert alert-<%= key == 'notice' ? 'success' : 'danger' %>">
    <span><%= value %></span>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_map.html.erb
<div class="col-md-9 col-12">
  <div id='map'></div>
</div>

<script>
  let map;
  let markers = [];
  function initMap() {
    const toiletPlaces = [
      // この部分はRailsからデータを取得
      <% toilet_places.each do |toilet_place| %>
        {
          lat: <%= toilet_place.latitude %>,
          lng: <%= toilet_place.longitude %>
        },
      <% end %>
    ];
    map = new google.maps.Map(document.getElementById('map'), {
      center: { lat: toiletPlaces[0].lat, lng: toiletPlaces[0].lng },
      zoom: 12,
    });
    
    const image = "<%= asset_path('toilet.png') %>";

    toiletPlaces.forEach(place => {
      const marker = new google.maps.Marker({
        position: { lat: place.lat, lng: place.lng },
        map: map,
        icon: image,
      });
      markers.push(marker);
    });

    const directionsService = new google.maps.DirectionsService();
    const directionsRenderer = new google.maps.DirectionsRenderer();
    directionsRenderer.setMap(map);
    navigator.geolocation.getCurrentPosition(function(position) {
      const currentLocation = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
      map.setCenter(currentLocation);
      const currentMarker = new google.maps.Marker({
        position: currentLocation,
        map: map,
      });
      markers.push(currentMarker);
      
      // 最短距離のtoilet_placeを見つける（簡単な例）
      let shortestDistance = Number.MAX_VALUE;
      let closestPlace = null;
      toiletPlaces.forEach(place => {
        const toiletLocation = new google.maps.LatLng(place.lat, place.lng);
        const distance = google.maps.geometry.spherical.computeDistanceBetween(currentLocation, toiletLocation);
        if (distance < shortestDistance) {
          shortestDistance = distance;
          closestPlace = place;
        }
      });

      // 最短距離のtoilet_placeまでのルートを取得
      const request = {
        origin: currentLocation,
        destination: new google.maps.LatLng(closestPlace.lat, closestPlace.lng),
        travelMode: 'WALKING',
      };
      directionsService.route(request, function(result, status) {
        if (status === 'OK') {
          google.maps.event.addListenerOnce(directionsRenderer, 'directions_changed', function() {
            const duration = result.routes[0].legs[0].duration.text;
            const steps = result.routes[0].legs[0].steps;
            let instructions = '道順:\n';
            steps.forEach((step, index) => {
              instructions += `${index + 1}. ${step.instructions} (距離: ${step.distance.text})\n`;
            });

            document.getElementById('routeDetails').innerHTML = `
              <p>所要時間: ${duration}</p>
              <pre>${instructions}</pre>
            `;
          });

          directionsRenderer.setDirections(result);
        }
      });
    }, function(error) {
      console.log("Error occurred. Error code: " + error.code);
    });
  }
  </script>

<script src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAP_API_KEY'] %>&callback=initMap" async defer></script>

app/views/shared/_title.html.erb
  <div class='d-flex align-items-center mt-3 me-5'>
    <div>
      <%= link_to (image_tag 'toilet_nav.png') , root_path %>
    </div>
    <h1 class='flex-shrink-0'>トイレナビ</h1>
  </div>

app/views/toilet_places/_form.html.erb
<%= simple_form_for toilet_place, html: { class: 'mt-3' } do |f| %>
  <% if f.object.errors.any? %>
    <% f.object.errors.full_messages.each do |msg| %>
      <div class='alert alert-danger'><%= msg %></div>
    <% end %>
  <% end %>

  <%= f.input :name %>
  <%= f.input :address, placeholder: '土地名または、住所を入力してください' %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/toilet_places/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-3 col-12 scrollable-sidebar">
      <%= render 'shared/title' %>
      <ul class="nav nav-tabs" id="myTabs">
        <li class="nav-item">
          <a class="nav-link active" id="tab1-tab" data-bs-toggle="tab" href="#tab1">経路案内</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="tab2-tab" data-bs-toggle="tab" href="#tab2">編集</a>
        </li>
                <li class="nav-item">
          <a class="nav-link" id="tab3-tab" data-bs-toggle="tab" href="#tab3">各リンク</a>
        </li>
      </ul>

      <div class="tab-content">
        <div class="tab-pane active" id="tab1">
          <div id="routeDetails"></div>
        </div>
        <div class="tab-pane" id="tab2">
          <%= render 'form', toilet_place: @toilet_place %>
        </div>
        <div class="tab-pane" id="tab3">
          <% if user_signed_in? %>
          <ul class='p-4 ms-4'>
            <li class='mb-3'><%= link_to 'トイレの一覧画面', toilet_places_path%></li>
            <li class='mb-3'><%= link_to 'トイレの場所登録', new_toilet_place_path %></li>
            <li class='mb-3'><%= link_to 'ログアウト', destroy_user_session_path, data: { turbo_method: :delete } %></li>
          </ul>
          <% else %>
          <ul>
            <li class='mb-3'><%= link_to 'アカウント登録', new_user_registration_path %></li>
            <li class='mb-3'><%= link_to 'ログイン', new_user_session_path %></li>
          </ul>
          <% end %>
        </div>
      </div>
    </div>
      <%= render 'shared/map', toilet_places: @toilet_places %>
  </div>
</div>

app/views/toilet_places/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-3 col-12 scrollable-sidebar">
      <%= render 'shared/title' %>
      <button class='js-startBtn'>🎤</button>
      <%= search_form_for @q, url: toilet_places_path, class: 'mt-3', html: { name: 'searchForm' } do |f| %>
        <%= f.label :address_cont, '住所', class: 'form-label' %>
        <%= f.search_field :address_cont, class: 'form-control' %>
        <%= f.submit '検索', class: 'btn btn-primary btn-sm my-2' %>
      <% end %>

      <ul class="nav nav-tabs" id="myTabs">
        <li class="nav-item active">
          <a class="nav-link" id="tab1-tab" data-bs-toggle="tab" href="#tab1">経路案内</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="tab2-tab" data-bs-toggle="tab" href="#tab2">トイレ一覧</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="tab3-tab" data-bs-toggle="tab" href="#tab3">各リンク</a>
        </li>
      </ul>

      <div class="tab-content">
        <div class="tab-pane active" id="tab1">
          <div id="routeDetails"></div>
        </div>

        <div class="tab-pane" id="tab2">
          <% @results.each do |toilet_place| %>
            <div class="border-bottom d-flex align-items-center">
              <div class='py-2'>
                <%= link_to toilet_place.name, toilet_place_path(toilet_place), data: { 'turbo': 'false' }%>
                <p><%= toilet_place.address %></p>
              </div>
              <% if user_signed_in? && current_user.toilet_places.include?(toilet_place) %>
              <div class="mt-2 ms-auto flex-shrink-0">
                <%= link_to '編集', edit_toilet_place_path(toilet_place), class: "btn btn-secondary btn-sm" %>
                <%= link_to '削除', toilet_place_path(toilet_place), data: { turbo_method: :delete, turbo_confirm: '本当に削除して良いですか？' }, class: "btn btn-danger btn-sm" %>
              </div>
              <% end %>
            </div>
          <% end %>
          <div class='mt-3'>
            <%= paginate @toilet_places, window: 2 %>
          </div>
        </div>

        <div class="tab-pane" id="tab3">
          <% if user_signed_in? %>
            <ul class='p-4 ms-4'>
              <li class='mb-3'><%= link_to 'トイレの場所登録', new_toilet_place_path %></li>
              <li class='mb-3'><%= link_to 'ログアウト', destroy_user_session_path, data: { turbo_method: :delete } %></li>
            </ul>
          <% else %>
            <ul class='p-4 ms-4'>
              <li class='mb-3'><%= link_to 'アカウント登録', new_user_registration_path, class: "mb-2"%></li>
              <li class='mb-3'><%= link_to 'ログイン', new_user_session_path, class: "mb-2"%></li>
            </ul>
          <% end %>
        </div>
      </div>
    </div>
      <%= render 'shared/map', toilet_places: @toilet_places %>
  </div>
</div>

app/views/toilet_places/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-3 col-12 scrollable-sidebar">
      <%= render 'shared/title' %>
      <ul class="nav nav-tabs" id="myTabs">
        <li class="nav-item">
          <a class="nav-link active" id="tab1-tab" data-bs-toggle="tab" href="#tab1">経路案内</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="tab2-tab" data-bs-toggle="tab" href="#tab2">新規登録</a>
        </li>
                <li class="nav-item">
          <a class="nav-link" id="tab3-tab" data-bs-toggle="tab" href="#tab3">各リンク</a>
        </li>
      </ul>

      <div class="tab-content">
        <div class="tab-pane active" id="tab1">
          <div id="routeDetails"></div>
        </div>
        <div class="tab-pane" id="tab2">
          <%= render 'form', toilet_place: @toilet_place %>
        </div>
        <div class="tab-pane" id="tab3">
          <% if user_signed_in? %>
            <ul class='p-4 ms-4'>
              <li class='mb-3'><%= link_to 'トイレの一覧画面', toilet_places_path%></li>
              <li class='mb-3'><%= link_to 'トイレの場所登録', new_toilet_place_path %></li>
              <li class='mb-3'><%= link_to 'ログアウト', destroy_user_session_path, data: { turbo_method: :delete } %></li>
            </ul>
          <% else %>
            <ul class='p-4 ms-4'>
              <li class='mb-3'><%= link_to 'アカウント登録', new_user_registration_path, class: "mb-2"%></li>
              <li class='mb-3'><%= link_to 'ログイン', new_user_session_path, class: "mb-2"%></li>
            </ul>ink_to 'ログイン', new_user_session_path, class: "dropdown-item"%></p>
          <% end %>
        </div>
      </div>
    </div>
      <%= render 'shared/map', toilet_places: @toilet_places %>
  </div>
</div>

app/views/toilet_places/show.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-3 col-12">
      <%= render 'shared/title' %>
      <ul class="nav nav-tabs mt-3" id="myTabs">
        <li class="nav-item">
          <a class="nav-link active" id="tab1-tab" data-bs-toggle="tab" href="#tab1">経路案内</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="tab2-tab" data-bs-toggle="tab" href="#tab2">詳細</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" id="tab3-tab" data-bs-toggle="tab" href="#tab3">各リンク</a>
        </li>
      </ul>
      <div class="tab-content">
        <div class="tab-pane active" id="tab1">
          <div id="routeDetails"></div>
        </div>

        <div class="tab-pane" id="tab2">
          <div>
            <h3 class='mt-2'><%= @toilet_place.name %></h3>
            <span class='ms-1'><%= @toilet_place.address %></span>
            <hr>
          </div>

          <%if user_signed_in? %>
            <%= simple_form_for @review, url: toilet_place_reviews_path(@toilet_place)  do |f|%>
              <%= f.input :content, input_html: { rows: 5 } %>
              <%= f.input :toilet_place_id, as: :hidden, input_html: { value: @toilet_place.id } %>
              <%= f.button :submit, class: 'btn btn-primary' %>
            <% end %>
          <% end %>

          <% @reviews.each do |review| %>
            <div class='card my-4'>
              <div class='card-header'>
                <%= review.user.name %>
              </div>
              <div class='card-body d-flex'>
                <div>
                  <%= review.content %>
                </div>
              <% if user_signed_in? && current_user.reviews.include?(review) %>
                <div class='ms-auto flex-shrink-0 mt-auto'>
                  <!--<%= link_to '編集', edit_toilet_place_review_path(review.toilet_place_id, review), class: 'btn btn-secondary btn-sm me-1' %>-->
                  <%= link_to '削除', toilet_place_review_path(review.toilet_place_id, review), data: { turbo_method: :delete, turbo_confirm: '本当に削除して良いですか？' }, class: 'btn btn-danger btn-sm'  %>
                </div>
              <% end %>
              </div>
            </div>
          <% end %>
        </div>
        
        <div class="tab-pane" id="tab3">
          <% if user_signed_in? %>
            <ul class='p-4 ms-4'>
              <li class='mb-3'><%= link_to 'トイレの一覧画面', toilet_places_path%></li>
              <li class='mb-3'><%= link_to 'トイレの場所登録', new_toilet_place_path %></li>
              <li class='mb-3'><%= link_to 'ログアウト', destroy_user_session_path, data: { turbo_method: :delete } %></li>
            </ul>
          <% else %>
            <ul class='p-4 ms-4'>
              <li class='mb-3'><%= link_to 'トイレの一覧画面', toilet_places_path%></li>
              <li class='mb-3'><%= link_to 'アカウント登録', new_user_registration_path %></li>
              <li class='mb-3'><%= link_to 'ログイン', new_user_session_path %></li>
            </ul>
          <% end %>
        </div>
      </div>
    </div>
    <%= render 'shared/map', toilet_places: @toilet_places %>
  </div>
</div>

app/views/top/index.html.erb
<div class="container-fluid">
  <div class="row">
    <%= render 'layouts/sidebar', toilet_places: @toilet_places %>
    <%= render 'shared/map', toilet_places: @toilet_places %>
  </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "ログイン", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "アカウント登録", new_registration_path(resource_name) %><br />
<% end %>

<!--<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>-->
<!--  <%= link_to "パスワード?", new_password_path(resource_name) %><br />-->
<!--<% end %>-->

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>